const { init, run, get } = require('../backend/db/database');
const { hashPassword } = require('../backend/utils/security');
const env = require('../backend/config/env');

const cars = [
  {
    "brand": "BMW",
    "model": "X5",
    "title": "BMW X5 Premium Paket #1",
    "category": "SUV",
    "price_daily": 980,
    "price_weekly": 5880,
    "price_monthly": 23520,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=1",
    "plate": "34 RC 1001",
    "mileage": 850,
    "deposit": 1960,
    "status": "available",
    "featured": 1,
    "description": "BMW X5 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Audi",
    "model": "A6",
    "title": "Audi A6 Premium Paket #2",
    "category": "Lüks",
    "price_daily": 1610,
    "price_weekly": 9660,
    "price_monthly": 38640,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=2",
    "plate": "34 RC 1002",
    "mileage": 1700,
    "deposit": 3220,
    "status": "available",
    "featured": 1,
    "description": "Audi A6 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Tesla",
    "model": "Model 3",
    "title": "Tesla Model 3 Premium Paket #3",
    "category": "Elektrikli",
    "price_daily": 990,
    "price_weekly": 5940,
    "price_monthly": 23760,
    "year": 2023,
    "fuel": "Elektrik",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=3",
    "plate": "34 RC 1003",
    "mileage": 2550,
    "deposit": 1980,
    "status": "available",
    "featured": 1,
    "description": "Tesla Model 3 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Renault",
    "model": "Clio",
    "title": "Renault Clio Premium Paket #4",
    "category": "Ekonomi",
    "price_daily": 1170,
    "price_weekly": 7020,
    "price_monthly": 28080,
    "year": 2024,
    "fuel": "Benzin",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=4",
    "plate": "34 RC 1004",
    "mileage": 3400,
    "deposit": 2340,
    "status": "available",
    "featured": 1,
    "description": "Renault Clio günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Toyota",
    "model": "RAV4",
    "title": "Toyota RAV4 Premium Paket #5",
    "category": "SUV",
    "price_daily": 1700,
    "price_weekly": 10200,
    "price_monthly": 40800,
    "year": 2025,
    "fuel": "Hibrit",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=5",
    "plate": "34 RC 1005",
    "mileage": 4250,
    "deposit": 3400,
    "status": "available",
    "featured": 1,
    "description": "Toyota RAV4 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Volkswagen",
    "model": "Golf",
    "title": "Volkswagen Golf Premium Paket #6",
    "category": "Konfor",
    "price_daily": 1530,
    "price_weekly": 9180,
    "price_monthly": 36720,
    "year": 2020,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=6",
    "plate": "34 RC 1006",
    "mileage": 5100,
    "deposit": 3060,
    "status": "available",
    "featured": 1,
    "description": "Volkswagen Golf günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Hyundai",
    "model": "Tucson",
    "title": "Hyundai Tucson Premium Paket #7",
    "category": "SUV",
    "price_daily": 2060,
    "price_weekly": 12360,
    "price_monthly": 49440,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=7",
    "plate": "34 RC 1007",
    "mileage": 5950,
    "deposit": 4120,
    "status": "available",
    "featured": 1,
    "description": "Hyundai Tucson günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Fiat",
    "model": "Egea",
    "title": "Fiat Egea Premium Paket #8",
    "category": "Ekonomi",
    "price_daily": 1890,
    "price_weekly": 11340,
    "price_monthly": 45360,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=8",
    "plate": "34 RC 1008",
    "mileage": 6800,
    "deposit": 3780,
    "status": "available",
    "featured": 1,
    "description": "Fiat Egea günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Porsche",
    "model": "Cayenne",
    "title": "Porsche Cayenne Premium Paket #9",
    "category": "Lüks",
    "price_daily": 2870,
    "price_weekly": 17220,
    "price_monthly": 68880,
    "year": 2023,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=9",
    "plate": "34 RC 1009",
    "mileage": 7650,
    "deposit": 5740,
    "status": "available",
    "featured": 1,
    "description": "Porsche Cayenne günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Range Rover",
    "model": "Sport",
    "title": "Range Rover Sport Premium Paket #10",
    "category": "SUV",
    "price_daily": 2600,
    "price_weekly": 15600,
    "price_monthly": 62400,
    "year": 2024,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=10",
    "plate": "34 RC 1010",
    "mileage": 8500,
    "deposit": 5200,
    "status": "available",
    "featured": 0,
    "description": "Range Rover Sport günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Peugeot",
    "model": "3008",
    "title": "Peugeot 3008 Premium Paket #11",
    "category": "SUV",
    "price_daily": 2780,
    "price_weekly": 16680,
    "price_monthly": 66720,
    "year": 2025,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=11",
    "plate": "34 RC 1011",
    "mileage": 9350,
    "deposit": 5560,
    "status": "available",
    "featured": 0,
    "description": "Peugeot 3008 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Mercedes",
    "model": "C200",
    "title": "Mercedes C200 Premium Paket #12",
    "category": "Lüks",
    "price_daily": 1250,
    "price_weekly": 7500,
    "price_monthly": 30000,
    "year": 2020,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=12",
    "plate": "34 RC 1012",
    "mileage": 10200,
    "deposit": 2500,
    "status": "available",
    "featured": 0,
    "description": "Mercedes C200 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "BMW",
    "model": "X5",
    "title": "BMW X5 Premium Paket #13",
    "category": "SUV",
    "price_daily": 980,
    "price_weekly": 5880,
    "price_monthly": 23520,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=13",
    "plate": "34 RC 1013",
    "mileage": 11050,
    "deposit": 1960,
    "status": "available",
    "featured": 0,
    "description": "BMW X5 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Audi",
    "model": "A6",
    "title": "Audi A6 Premium Paket #14",
    "category": "Lüks",
    "price_daily": 1610,
    "price_weekly": 9660,
    "price_monthly": 38640,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=14",
    "plate": "34 RC 1014",
    "mileage": 11900,
    "deposit": 3220,
    "status": "available",
    "featured": 0,
    "description": "Audi A6 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Tesla",
    "model": "Model 3",
    "title": "Tesla Model 3 Premium Paket #15",
    "category": "Elektrikli",
    "price_daily": 990,
    "price_weekly": 5940,
    "price_monthly": 23760,
    "year": 2023,
    "fuel": "Elektrik",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=15",
    "plate": "34 RC 1015",
    "mileage": 12750,
    "deposit": 1980,
    "status": "available",
    "featured": 0,
    "description": "Tesla Model 3 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Renault",
    "model": "Clio",
    "title": "Renault Clio Premium Paket #16",
    "category": "Ekonomi",
    "price_daily": 1170,
    "price_weekly": 7020,
    "price_monthly": 28080,
    "year": 2024,
    "fuel": "Benzin",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=16",
    "plate": "34 RC 1016",
    "mileage": 13600,
    "deposit": 2340,
    "status": "available",
    "featured": 0,
    "description": "Renault Clio günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Toyota",
    "model": "RAV4",
    "title": "Toyota RAV4 Premium Paket #17",
    "category": "SUV",
    "price_daily": 1700,
    "price_weekly": 10200,
    "price_monthly": 40800,
    "year": 2025,
    "fuel": "Hibrit",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=17",
    "plate": "34 RC 1017",
    "mileage": 14450,
    "deposit": 3400,
    "status": "available",
    "featured": 0,
    "description": "Toyota RAV4 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Volkswagen",
    "model": "Golf",
    "title": "Volkswagen Golf Premium Paket #18",
    "category": "Konfor",
    "price_daily": 1530,
    "price_weekly": 9180,
    "price_monthly": 36720,
    "year": 2020,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=18",
    "plate": "34 RC 1018",
    "mileage": 15300,
    "deposit": 3060,
    "status": "available",
    "featured": 0,
    "description": "Volkswagen Golf günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Hyundai",
    "model": "Tucson",
    "title": "Hyundai Tucson Premium Paket #19",
    "category": "SUV",
    "price_daily": 2060,
    "price_weekly": 12360,
    "price_monthly": 49440,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=19",
    "plate": "34 RC 1019",
    "mileage": 16150,
    "deposit": 4120,
    "status": "available",
    "featured": 0,
    "description": "Hyundai Tucson günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Fiat",
    "model": "Egea",
    "title": "Fiat Egea Premium Paket #20",
    "category": "Ekonomi",
    "price_daily": 1890,
    "price_weekly": 11340,
    "price_monthly": 45360,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=20",
    "plate": "34 RC 1020",
    "mileage": 17000,
    "deposit": 3780,
    "status": "available",
    "featured": 0,
    "description": "Fiat Egea günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Porsche",
    "model": "Cayenne",
    "title": "Porsche Cayenne Premium Paket #21",
    "category": "Lüks",
    "price_daily": 2870,
    "price_weekly": 17220,
    "price_monthly": 68880,
    "year": 2023,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=21",
    "plate": "34 RC 1021",
    "mileage": 17850,
    "deposit": 5740,
    "status": "available",
    "featured": 0,
    "description": "Porsche Cayenne günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Range Rover",
    "model": "Sport",
    "title": "Range Rover Sport Premium Paket #22",
    "category": "SUV",
    "price_daily": 2600,
    "price_weekly": 15600,
    "price_monthly": 62400,
    "year": 2024,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=22",
    "plate": "34 RC 1022",
    "mileage": 18700,
    "deposit": 5200,
    "status": "available",
    "featured": 0,
    "description": "Range Rover Sport günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Peugeot",
    "model": "3008",
    "title": "Peugeot 3008 Premium Paket #23",
    "category": "SUV",
    "price_daily": 2780,
    "price_weekly": 16680,
    "price_monthly": 66720,
    "year": 2025,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=23",
    "plate": "34 RC 1023",
    "mileage": 19550,
    "deposit": 5560,
    "status": "available",
    "featured": 0,
    "description": "Peugeot 3008 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Mercedes",
    "model": "C200",
    "title": "Mercedes C200 Premium Paket #24",
    "category": "Lüks",
    "price_daily": 1250,
    "price_weekly": 7500,
    "price_monthly": 30000,
    "year": 2020,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=24",
    "plate": "34 RC 1024",
    "mileage": 20400,
    "deposit": 2500,
    "status": "available",
    "featured": 0,
    "description": "Mercedes C200 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "BMW",
    "model": "X5",
    "title": "BMW X5 Premium Paket #25",
    "category": "SUV",
    "price_daily": 980,
    "price_weekly": 5880,
    "price_monthly": 23520,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=25",
    "plate": "34 RC 1025",
    "mileage": 21250,
    "deposit": 1960,
    "status": "available",
    "featured": 0,
    "description": "BMW X5 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Audi",
    "model": "A6",
    "title": "Audi A6 Premium Paket #26",
    "category": "Lüks",
    "price_daily": 1610,
    "price_weekly": 9660,
    "price_monthly": 38640,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=26",
    "plate": "34 RC 1026",
    "mileage": 22100,
    "deposit": 3220,
    "status": "available",
    "featured": 0,
    "description": "Audi A6 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Tesla",
    "model": "Model 3",
    "title": "Tesla Model 3 Premium Paket #27",
    "category": "Elektrikli",
    "price_daily": 990,
    "price_weekly": 5940,
    "price_monthly": 23760,
    "year": 2023,
    "fuel": "Elektrik",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=27",
    "plate": "34 RC 1027",
    "mileage": 22950,
    "deposit": 1980,
    "status": "available",
    "featured": 0,
    "description": "Tesla Model 3 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Renault",
    "model": "Clio",
    "title": "Renault Clio Premium Paket #28",
    "category": "Ekonomi",
    "price_daily": 1170,
    "price_weekly": 7020,
    "price_monthly": 28080,
    "year": 2024,
    "fuel": "Benzin",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=28",
    "plate": "34 RC 1028",
    "mileage": 23800,
    "deposit": 2340,
    "status": "available",
    "featured": 0,
    "description": "Renault Clio günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Toyota",
    "model": "RAV4",
    "title": "Toyota RAV4 Premium Paket #29",
    "category": "SUV",
    "price_daily": 1700,
    "price_weekly": 10200,
    "price_monthly": 40800,
    "year": 2025,
    "fuel": "Hibrit",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=29",
    "plate": "34 RC 1029",
    "mileage": 24650,
    "deposit": 3400,
    "status": "available",
    "featured": 0,
    "description": "Toyota RAV4 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Volkswagen",
    "model": "Golf",
    "title": "Volkswagen Golf Premium Paket #30",
    "category": "Konfor",
    "price_daily": 1530,
    "price_weekly": 9180,
    "price_monthly": 36720,
    "year": 2020,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=30",
    "plate": "34 RC 1030",
    "mileage": 25500,
    "deposit": 3060,
    "status": "available",
    "featured": 0,
    "description": "Volkswagen Golf günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Hyundai",
    "model": "Tucson",
    "title": "Hyundai Tucson Premium Paket #31",
    "category": "SUV",
    "price_daily": 2060,
    "price_weekly": 12360,
    "price_monthly": 49440,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=31",
    "plate": "34 RC 1031",
    "mileage": 26350,
    "deposit": 4120,
    "status": "available",
    "featured": 0,
    "description": "Hyundai Tucson günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Fiat",
    "model": "Egea",
    "title": "Fiat Egea Premium Paket #32",
    "category": "Ekonomi",
    "price_daily": 1890,
    "price_weekly": 11340,
    "price_monthly": 45360,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=32",
    "plate": "34 RC 1032",
    "mileage": 27200,
    "deposit": 3780,
    "status": "available",
    "featured": 0,
    "description": "Fiat Egea günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Porsche",
    "model": "Cayenne",
    "title": "Porsche Cayenne Premium Paket #33",
    "category": "Lüks",
    "price_daily": 2870,
    "price_weekly": 17220,
    "price_monthly": 68880,
    "year": 2023,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=33",
    "plate": "34 RC 1033",
    "mileage": 28050,
    "deposit": 5740,
    "status": "available",
    "featured": 0,
    "description": "Porsche Cayenne günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Range Rover",
    "model": "Sport",
    "title": "Range Rover Sport Premium Paket #34",
    "category": "SUV",
    "price_daily": 2600,
    "price_weekly": 15600,
    "price_monthly": 62400,
    "year": 2024,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=34",
    "plate": "34 RC 1034",
    "mileage": 28900,
    "deposit": 5200,
    "status": "available",
    "featured": 0,
    "description": "Range Rover Sport günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Peugeot",
    "model": "3008",
    "title": "Peugeot 3008 Premium Paket #35",
    "category": "SUV",
    "price_daily": 2780,
    "price_weekly": 16680,
    "price_monthly": 66720,
    "year": 2025,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=35",
    "plate": "34 RC 1035",
    "mileage": 29750,
    "deposit": 5560,
    "status": "available",
    "featured": 0,
    "description": "Peugeot 3008 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Mercedes",
    "model": "C200",
    "title": "Mercedes C200 Premium Paket #36",
    "category": "Lüks",
    "price_daily": 1250,
    "price_weekly": 7500,
    "price_monthly": 30000,
    "year": 2020,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=36",
    "plate": "34 RC 1036",
    "mileage": 30600,
    "deposit": 2500,
    "status": "available",
    "featured": 0,
    "description": "Mercedes C200 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "BMW",
    "model": "X5",
    "title": "BMW X5 Premium Paket #37",
    "category": "SUV",
    "price_daily": 980,
    "price_weekly": 5880,
    "price_monthly": 23520,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=37",
    "plate": "34 RC 1037",
    "mileage": 31450,
    "deposit": 1960,
    "status": "available",
    "featured": 0,
    "description": "BMW X5 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Audi",
    "model": "A6",
    "title": "Audi A6 Premium Paket #38",
    "category": "Lüks",
    "price_daily": 1610,
    "price_weekly": 9660,
    "price_monthly": 38640,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=38",
    "plate": "34 RC 1038",
    "mileage": 32300,
    "deposit": 3220,
    "status": "available",
    "featured": 0,
    "description": "Audi A6 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Tesla",
    "model": "Model 3",
    "title": "Tesla Model 3 Premium Paket #39",
    "category": "Elektrikli",
    "price_daily": 990,
    "price_weekly": 5940,
    "price_monthly": 23760,
    "year": 2023,
    "fuel": "Elektrik",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=39",
    "plate": "34 RC 1039",
    "mileage": 33150,
    "deposit": 1980,
    "status": "available",
    "featured": 0,
    "description": "Tesla Model 3 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Renault",
    "model": "Clio",
    "title": "Renault Clio Premium Paket #40",
    "category": "Ekonomi",
    "price_daily": 1170,
    "price_weekly": 7020,
    "price_monthly": 28080,
    "year": 2024,
    "fuel": "Benzin",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=40",
    "plate": "34 RC 1040",
    "mileage": 34000,
    "deposit": 2340,
    "status": "available",
    "featured": 0,
    "description": "Renault Clio günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Toyota",
    "model": "RAV4",
    "title": "Toyota RAV4 Premium Paket #41",
    "category": "SUV",
    "price_daily": 1700,
    "price_weekly": 10200,
    "price_monthly": 40800,
    "year": 2025,
    "fuel": "Hibrit",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=41",
    "plate": "34 RC 1041",
    "mileage": 34850,
    "deposit": 3400,
    "status": "available",
    "featured": 0,
    "description": "Toyota RAV4 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Volkswagen",
    "model": "Golf",
    "title": "Volkswagen Golf Premium Paket #42",
    "category": "Konfor",
    "price_daily": 1530,
    "price_weekly": 9180,
    "price_monthly": 36720,
    "year": 2020,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=42",
    "plate": "34 RC 1042",
    "mileage": 35700,
    "deposit": 3060,
    "status": "available",
    "featured": 0,
    "description": "Volkswagen Golf günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Hyundai",
    "model": "Tucson",
    "title": "Hyundai Tucson Premium Paket #43",
    "category": "SUV",
    "price_daily": 2060,
    "price_weekly": 12360,
    "price_monthly": 49440,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=43",
    "plate": "34 RC 1043",
    "mileage": 36550,
    "deposit": 4120,
    "status": "available",
    "featured": 0,
    "description": "Hyundai Tucson günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Fiat",
    "model": "Egea",
    "title": "Fiat Egea Premium Paket #44",
    "category": "Ekonomi",
    "price_daily": 1890,
    "price_weekly": 11340,
    "price_monthly": 45360,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=44",
    "plate": "34 RC 1044",
    "mileage": 37400,
    "deposit": 3780,
    "status": "available",
    "featured": 0,
    "description": "Fiat Egea günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Porsche",
    "model": "Cayenne",
    "title": "Porsche Cayenne Premium Paket #45",
    "category": "Lüks",
    "price_daily": 2870,
    "price_weekly": 17220,
    "price_monthly": 68880,
    "year": 2023,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=45",
    "plate": "34 RC 1045",
    "mileage": 38250,
    "deposit": 5740,
    "status": "available",
    "featured": 0,
    "description": "Porsche Cayenne günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Range Rover",
    "model": "Sport",
    "title": "Range Rover Sport Premium Paket #46",
    "category": "SUV",
    "price_daily": 2600,
    "price_weekly": 15600,
    "price_monthly": 62400,
    "year": 2024,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=46",
    "plate": "34 RC 1046",
    "mileage": 39100,
    "deposit": 5200,
    "status": "available",
    "featured": 0,
    "description": "Range Rover Sport günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Peugeot",
    "model": "3008",
    "title": "Peugeot 3008 Premium Paket #47",
    "category": "SUV",
    "price_daily": 2780,
    "price_weekly": 16680,
    "price_monthly": 66720,
    "year": 2025,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=47",
    "plate": "34 RC 1047",
    "mileage": 39950,
    "deposit": 5560,
    "status": "available",
    "featured": 0,
    "description": "Peugeot 3008 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Mercedes",
    "model": "C200",
    "title": "Mercedes C200 Premium Paket #48",
    "category": "Lüks",
    "price_daily": 1250,
    "price_weekly": 7500,
    "price_monthly": 30000,
    "year": 2020,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=48",
    "plate": "34 RC 1048",
    "mileage": 40800,
    "deposit": 2500,
    "status": "available",
    "featured": 0,
    "description": "Mercedes C200 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "BMW",
    "model": "X5",
    "title": "BMW X5 Premium Paket #49",
    "category": "SUV",
    "price_daily": 980,
    "price_weekly": 5880,
    "price_monthly": 23520,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=49",
    "plate": "34 RC 1049",
    "mileage": 41650,
    "deposit": 1960,
    "status": "available",
    "featured": 0,
    "description": "BMW X5 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Audi",
    "model": "A6",
    "title": "Audi A6 Premium Paket #50",
    "category": "Lüks",
    "price_daily": 1610,
    "price_weekly": 9660,
    "price_monthly": 38640,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=50",
    "plate": "34 RC 1050",
    "mileage": 42500,
    "deposit": 3220,
    "status": "available",
    "featured": 0,
    "description": "Audi A6 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Tesla",
    "model": "Model 3",
    "title": "Tesla Model 3 Premium Paket #51",
    "category": "Elektrikli",
    "price_daily": 990,
    "price_weekly": 5940,
    "price_monthly": 23760,
    "year": 2023,
    "fuel": "Elektrik",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=51",
    "plate": "34 RC 1051",
    "mileage": 43350,
    "deposit": 1980,
    "status": "available",
    "featured": 0,
    "description": "Tesla Model 3 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Renault",
    "model": "Clio",
    "title": "Renault Clio Premium Paket #52",
    "category": "Ekonomi",
    "price_daily": 1170,
    "price_weekly": 7020,
    "price_monthly": 28080,
    "year": 2024,
    "fuel": "Benzin",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=52",
    "plate": "34 RC 1052",
    "mileage": 44200,
    "deposit": 2340,
    "status": "available",
    "featured": 0,
    "description": "Renault Clio günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Toyota",
    "model": "RAV4",
    "title": "Toyota RAV4 Premium Paket #53",
    "category": "SUV",
    "price_daily": 1700,
    "price_weekly": 10200,
    "price_monthly": 40800,
    "year": 2025,
    "fuel": "Hibrit",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=53",
    "plate": "34 RC 1053",
    "mileage": 45050,
    "deposit": 3400,
    "status": "available",
    "featured": 0,
    "description": "Toyota RAV4 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Volkswagen",
    "model": "Golf",
    "title": "Volkswagen Golf Premium Paket #54",
    "category": "Konfor",
    "price_daily": 1530,
    "price_weekly": 9180,
    "price_monthly": 36720,
    "year": 2020,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=54",
    "plate": "34 RC 1054",
    "mileage": 45900,
    "deposit": 3060,
    "status": "available",
    "featured": 0,
    "description": "Volkswagen Golf günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Hyundai",
    "model": "Tucson",
    "title": "Hyundai Tucson Premium Paket #55",
    "category": "SUV",
    "price_daily": 2060,
    "price_weekly": 12360,
    "price_monthly": 49440,
    "year": 2021,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=55",
    "plate": "34 RC 1055",
    "mileage": 46750,
    "deposit": 4120,
    "status": "available",
    "featured": 0,
    "description": "Hyundai Tucson günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Fiat",
    "model": "Egea",
    "title": "Fiat Egea Premium Paket #56",
    "category": "Ekonomi",
    "price_daily": 1890,
    "price_weekly": 11340,
    "price_monthly": 45360,
    "year": 2022,
    "fuel": "Dizel",
    "transmission": "Manuel",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=56",
    "plate": "34 RC 1056",
    "mileage": 47600,
    "deposit": 3780,
    "status": "available",
    "featured": 0,
    "description": "Fiat Egea günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Porsche",
    "model": "Cayenne",
    "title": "Porsche Cayenne Premium Paket #57",
    "category": "Lüks",
    "price_daily": 2870,
    "price_weekly": 17220,
    "price_monthly": 68880,
    "year": 2023,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Beyaz",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=57",
    "plate": "34 RC 1057",
    "mileage": 48450,
    "deposit": 5740,
    "status": "available",
    "featured": 0,
    "description": "Porsche Cayenne günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Range Rover",
    "model": "Sport",
    "title": "Range Rover Sport Premium Paket #58",
    "category": "SUV",
    "price_daily": 2600,
    "price_weekly": 15600,
    "price_monthly": 62400,
    "year": 2024,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Gri",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=58",
    "plate": "34 RC 1058",
    "mileage": 49300,
    "deposit": 5200,
    "status": "available",
    "featured": 0,
    "description": "Range Rover Sport günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Peugeot",
    "model": "3008",
    "title": "Peugeot 3008 Premium Paket #59",
    "category": "SUV",
    "price_daily": 2780,
    "price_weekly": 16680,
    "price_monthly": 66720,
    "year": 2025,
    "fuel": "Dizel",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Lacivert",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=59",
    "plate": "34 RC 1059",
    "mileage": 50150,
    "deposit": 5560,
    "status": "available",
    "featured": 0,
    "description": "Peugeot 3008 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  },
  {
    "brand": "Mercedes",
    "model": "C200",
    "title": "Mercedes C200 Premium Paket #60",
    "category": "Lüks",
    "price_daily": 1250,
    "price_weekly": 7500,
    "price_monthly": 30000,
    "year": 2020,
    "fuel": "Benzin",
    "transmission": "Otomatik",
    "seats": 5,
    "doors": 4,
    "color": "Siyah",
    "image_url": "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=900&auto=format&fit=crop&sig=60",
    "plate": "34 RC 1060",
    "mileage": 51000,
    "deposit": 2500,
    "status": "available",
    "featured": 0,
    "description": "Mercedes C200 günlük, haftalık ve aylık kiralama için hazır. Tam kasko, 7/24 destek ve WhatsApp rezervasyon."
  }
];

async function seed() {
  await init();
  const adminExists = await get('SELECT id FROM users WHERE email=?', [env.adminEmail]);
  if (!adminExists) {
    const hash = await hashPassword(env.adminPassword);
    await run('INSERT INTO users (name,email,phone,password_hash,role) VALUES (?,?,?,?,?)',
      ['Admin', env.adminEmail, '+1 639 569 7826', hash, 'admin']);
  }
  const count = await get('SELECT COUNT(*) count FROM cars');
  if (count.count === 0) {
    for (const c of cars) {
      await run(`INSERT INTO cars
      (brand,model,title,category,price_daily,price_weekly,price_monthly,year,fuel,transmission,seats,doors,color,image_url,plate,mileage,deposit,status,featured,description)
      VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
      [c.brand,c.model,c.title,c.category,c.price_daily,c.price_weekly,c.price_monthly,c.year,c.fuel,c.transmission,c.seats,c.doors,c.color,c.image_url,c.plate,c.mileage,c.deposit,c.status,c.featured,c.description]);
    }
  }
  await run('INSERT OR IGNORE INTO settings (key,value) VALUES (?,?)', ['whatsapp', env.whatsappNumber]);
  console.log('Seed tamamlandı. Admin:', env.adminEmail, '/', env.adminPassword);
}
seed().then(()=>process.exit()).catch(e=>{console.error(e);process.exit(1);});
